# Generated by Django 5.2.6 on 2025-09-26 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('SENT', 'Wysłano'), ('FAILED', 'Błąd')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject_template', models.TextField()),
                ('body_template', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('INFO', 'Informacja'), ('WARNING', 'Ostrzeżenie'), ('ERROR', 'Błąd'), ('DEBUG', 'Debug')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
