# Generated by Django 4.2.11 on 2025-09-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemlog',
            name='metadata',
        ),
        migrations.AddField(
            model_name='systemlog',
            name='metadata_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10),
        ),
    ]
