# Generated by Django 4.2.11 on 2025-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Tytuł')),
                ('content', models.CharField(max_length=10240, verbose_name='Treść')),
            ],
            options={
                'verbose_name': 'Informacja',
                'verbose_name_plural': 'Informacje',
                'ordering': ['id'],
            },
        ),
    ]
