# Generated by Django 4.2.11 on 2025-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='kontakt.ravadev@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(default='+48 000 000 000', max_length=20),
        ),
    ]
