# Generated by Django 5.2.6 on 2025-10-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0004_alter_message_image1_alter_message_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='Projects/')),
                ('image2', models.ImageField(upload_to='Projects/')),
                ('image3', models.ImageField(upload_to='Projects/')),
                ('link', models.URLField(blank=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Services.service')),
            ],
        ),
    ]
