# Generated by Django 5.2.6 on 2025-09-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phoneCode', models.PositiveSmallIntegerField()),
                ('phoneNumber', models.PositiveBigIntegerField()),
            ],
        ),
    ]
