# Generated by Django 4.2.25 on 2025-10-08 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_delete_message_alter_service_options_and_more'),
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='service',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.service'),
        ),
    ]
