# Generated by Django 5.2.6 on 2025-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service_image1_service_image2_service_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phoneCode', models.PositiveSmallIntegerField()),
                ('phoneNumber', models.PositiveBigIntegerField()),
                ('demand_level', models.CharField(choices=[('very_low', 'Bardzo niski'), ('low', 'Niski'), ('medium', 'Średni'), ('medium_high', 'Średni-wysoki'), ('high', 'Wysoki'), ('very_high', 'Bardzo wysoki')], max_length=20, verbose_name='Poziom popytu')),
                ('demand_coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Współczynnik popytu')),
                ('local_supply', models.CharField(choices=[('none', 'Brak'), ('very_low', 'Bardzo niska'), ('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka')], max_length=20, verbose_name='Podaż lokalna')),
                ('supply_coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Współczynnik podaży')),
                ('market_price_range', models.CharField(max_length=100, verbose_name='Zakres cen rynkowych')),
                ('price_coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Współczynnik ceny')),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena minimalna rynkowa')),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena maksymalna rynkowa')),
                ('local_price_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lokalna cena minimalna')),
                ('local_price_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lokalna cena maksymalna')),
                ('market_relation', models.TextField(verbose_name='Relacja rynkowa')),
                ('range_number_1', models.IntegerField(verbose_name='Numer zakresu 1')),
                ('range_number_2', models.IntegerField(verbose_name='Numer zakresu 2')),
                ('valuation_coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Współczynnik wyceny')),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wycena')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_min',
        ),
        migrations.AddField(
            model_name='service',
            name='feature_1_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Nazwa cechy 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='feature_1_ranges',
            field=models.CharField(default=0, max_length=200, verbose_name='Zakresy cechy 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='feature_2_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Nazwa cechy 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='feature_2_ranges',
            field=models.CharField(default=0, max_length=200, verbose_name='Zakresy cechy 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='nr',
            field=models.IntegerField(default=0, unique=True, verbose_name='Numer usługi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Opis usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nazwa usługi'),
        ),
    ]
