# Generated by Django 5.2.6 on 2025-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_message_remove_service_image1_remove_service_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
    ]
