# Generated by Django 5.2.7 on 2025-10-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_message_image1_alter_message_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AddField(
            model_name='service',
            name='demand_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Współczynnik popytu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='demand_level',
            field=models.CharField(choices=[('very_low', 'Bardzo niski'), ('low', 'Niski'), ('medium', 'Średni'), ('medium_high', 'Średni-wysoki'), ('high', 'Wysoki'), ('very_high', 'Bardzo wysoki')], default=1, max_length=20, verbose_name='Poziom popytu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='local_price_max',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Lokalna cena maksymalna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='local_price_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Lokalna cena minimalna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='local_supply',
            field=models.CharField(choices=[('none', 'Brak'), ('very_low', 'Bardzo niska'), ('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka')], default=1, max_length=20, verbose_name='Podaż lokalna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='market_price_range',
            field=models.CharField(default=1, max_length=100, verbose_name='Zakres cen rynkowych'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='market_relation',
            field=models.TextField(default=1, verbose_name='Relacja rynkowa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Współczynnik ceny'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cena maksymalna rynkowa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cena minimalna rynkowa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='range_number_1',
            field=models.IntegerField(default=1, verbose_name='Numer zakresu 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='range_number_2',
            field=models.IntegerField(default=1, verbose_name='Numer zakresu 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='supply_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Współczynnik podaży'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Wycena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='valuation_coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Współczynnik wyceny'),
            preserve_default=False,
        ),
    ]
