# Generated by Django 4.2.11 on 2025-10-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_delete_message_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa dziedziny')),
                ('description', models.CharField(max_length=200, verbose_name='Opis dziedziny')),
            ],
            options={
                'verbose_name': 'Pole',
                'verbose_name_plural': 'Pola',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.field', verbose_name='Dziedzina'),
        ),
    ]
