# Generated by Django 4.2.11 on 2025-10-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_field_service_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['id'], 'verbose_name': 'Dziedzina', 'verbose_name_plural': 'Dziedziny'},
        ),
    ]
