# Generated by Django 4.2.11 on 2025-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_alter_field_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Długi opis usługi'),
        ),
    ]
